version: "3.8"
services:
  brain:
    build:
      args:
        NETWORK: gnosis
    image: brain.web3signer-gnosis.dnp.dappnode.eth:1.0.14
  web3signer:
    build:
      args:
        NETWORK: gnosis
        PGPASSWORD: gnosis
        POSTGRES_DB: web3signer-gnosis
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-gnosis.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 100
    image: web3signer.web3signer-gnosis.dnp.dappnode.eth:1.0.14
  flyway:
    image: floriansaw/flyway-web3signer:25.3.0
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
  postgres:
    build:
      dockerfile: Dockerfile.debian
      args:
        POSTGRES_PASSWORD: gnosis
        PGPASSWORD: gnosis
        POSTGRES_DB: web3signer-gnosis
    image: postgres.web3signer-gnosis.dnp.dappnode.eth:1.0.14
