version: "3.8"
services:
  brain:
    build:
      args:
        NETWORK: holesky
    image: brain.web3signer-holesky.dnp.dappnode.eth:0.1.11
  web3signer:
    build:
      args:
        NETWORK: holesky
        PGPASSWORD: password
        POSTGRES_DB: web3signer
    healthcheck:
      test: >-
        curl -H 'Host: web3signer.web3signer-holesky.dappnode'
        http://localhost:9000/healthcheck
      interval: 5s
      timeout: 5s
      retries: 100
    image: web3signer.web3signer-holesky.dnp.dappnode.eth:0.1.11
  flyway:
    image: floriansaw/flyway-web3signer:25.3.0
    depends_on:
      postgres:
        condition: service_started
    restart: on-failure
  postgres:
    build:
      dockerfile: Dockerfile.alpine
      args:
        POSTGRES_PASSWORD: password
        PGPASSWORD: password
        POSTGRES_DB: web3signer
    image: postgres.web3signer-holesky.dnp.dappnode.eth:0.1.11
